# Numpy arrays

In [1]:
import numpy as np

## Create

In [4]:
n_rows = 2
n_cols = 4
my_array = np.zeros((n_rows, n_cols))
my_array

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
my_vector = np.ones(n_cols)
my_vector

array([1., 1., 1., 1.])

## Indexing

In [5]:
for row in range(n_rows):
    for col in range(n_cols):
        my_array[row, col] = 100*row+col
my_array

array([[  0.,   1.,   2.,   3.],
       [100., 101., 102., 103.]])

## Operations

In [7]:
my_array+42.0

array([[ 42.,  43.,  44.,  45.],
       [142., 143., 144., 145.]])

In [9]:
my_array*42

array([[   0.,   42.,   84.,  126.],
       [4200., 4242., 4284., 4326.]])

In [13]:
np.dot(my_array, my_vector)

array([  6., 406.])