# Numpy arrays

In [1]:
import numpy as np

## Create

In [7]:
n_rows = 4
n_cols = 2
my_array = np.zeros((n_rows, n_cols))
my_array

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
my_vector = np.ones(n_cols)
my_vector

array([1., 1.])

In [9]:
diagonal_matrix = np.diag([1,2,3])
diagonal_matrix

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
shifted_diag = np.diag([1,2,3],1)
shifted_diag

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

## Indexing

In [11]:
for row in range(n_rows):
    for col in range(n_cols):
        my_array[row, col] = 100*row+col
my_array

array([[  0.,   1.],
       [100., 101.],
       [200., 201.],
       [300., 301.]])

## Operations

In [12]:
my_array+42.0

array([[ 42.,  43.],
       [142., 143.],
       [242., 243.],
       [342., 343.]])

In [13]:
my_array*42

array([[    0.,    42.],
       [ 4200.,  4242.],
       [ 8400.,  8442.],
       [12600., 12642.]])

In [14]:
np.dot(my_array, my_vector)

array([  1., 201., 401., 601.])

# Solve:
$$\underline{\underline{M}}\cdot\underline{x}=\underline{v}$$

In [19]:
M = np.array([[1,1], [1, -1]])
v = np.array([179, 95])
print(f"M={M}\n v={v}")

M=[[ 1  1]
 [ 1 -1]]
 v=[179  95]


In [21]:
from scipy import linalg
x = linalg.solve(M, v)
print(f"Solution: x={x}")

Solution: x=[137.  42.]
