In [1]:
import os 
import sys

In [2]:
sys.path.append("..\..")

In [3]:
from src.market_data import *

In [4]:
MarketData.initialize()

In [5]:
help(Stock.TEST_COMPANY)

No Python documentation found for <Stock.TEST_COMPANY: 'TEST_COMPANY'>.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.



In [6]:
from src.pricer import *

In [7]:
model = FlatVolModel(Stock.TEST_COMPANY)
expiry = 1.0
strike = 100
contract = EuropeanContract(Stock.TEST_COMPANY, PutCallFwd.PUT, LongShort.LONG, strike, expiry)

In [19]:
params = PDEParams(method = "cranknicolson")

In [43]:
params = PDEParams(method = "implicit")

In [20]:
params = PDEParams(und_step= 2, time_step = 1/1200, stock_min = 0, stock_max= 200, method= "explicit")

In [21]:
PDEpricer = EuropeanPDEPricer(contract, model, params)

In [16]:
(PDEpricer._bsPDE.measure_of_stock)

array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,
        11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,
        22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,
        33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,
        44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
        55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,
        66.,  67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,
        77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,
        88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,
        99., 100.])

In [27]:
((PDEpricer.grid)[:,0])

array([ 95.12294245,  95.12690599,  95.13086969, ...,  99.99166701,
        99.99583342, 100.        ])

In [18]:
PDEpricer.calc_fair_value()

9.349075221635864

In [48]:
PDEpricer.calc_fair_value()

14.223444387300706

In [30]:
PDEpricer.calc_fair_value()

19.884721608868233

In [12]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.zeros(10-1)[1]

0.0

In [17]:
PDEpricer.grid

array([[105.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -90.36679533],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -90.41199002],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -90.45720732],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -94.90504748],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -94.95251187],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        , -95.        ]])

In [14]:
import numpy as np
(np.floor(0.50))

0.0

In [29]:
(PDEpricer._bsPDE.ns_steps)

400

In [13]:
PDEpricer.nt_steps

100

In [14]:
PDEpricer.ns_steps

400

In [15]:
len(PDEpricer._bsPDE.grid)

101

In [17]:
bs = BlackScholesPDE(model, params)

In [19]:
len(bs.grid)

101

In [24]:
P, Q, R = bs.tridiagonal_matrix()

In [27]:
len(R)

399

In [23]:
bs.implicit_method()

ValueError: shapes (399,399) and (401,) not aligned: 399 (dim 1) != 401 (dim 0)

In [ ]:
np.dot(R, grid[j, :])

In [22]:
bs.grid

array([[ 1.05000000e+002,  1.04500000e+002,  1.04000000e+002, ...,
         0.00000000e+000,  0.00000000e+000, -9.03667953e+001],
       [ 0.00000000e+000,  1.04447500e+002,  1.03947500e+002, ...,
         0.00000000e+000, -1.54232557e+003, -9.04119900e+001],
       [ 0.00000000e+000,  1.04410078e+002,  1.03895026e+002, ...,
        -2.61920787e+004,  4.92546068e+004, -9.04572073e+001],
       ...,
       [ 0.00000000e+000,  1.00855151e+002,  9.89730318e+001, ...,
        -1.41820418e+177,  7.64448089e+176, -9.49050475e+001],
       [ 0.00000000e+000,  1.00818517e+002,  9.89229478e+001, ...,
         9.10988129e+178, -4.90998137e+178, -9.49525119e+001],
       [ 0.00000000e+000,  1.00781891e+002,  9.88728880e+001, ...,
        -5.85201783e+180,  3.15378591e+180, -9.50000000e+001]])

<img src="lesson_pages/1.png">

<img src="lesson_pages/2.png">

<img src="lesson_pages/3.png">

<img src="lesson_pages/4.png">

<img src="lesson_pages/5.png">

# EXAMPLE WITH EXPLICIT METHOD

In [10]:
# Create European Contract
# Create Market Model
# Create PDEParams
# Create GenericPDEPricer
# Calculate FV and Greeks based on Explicit method
# Visualize the Call and Put prices in 2D and 3D

<img src="lesson_pages/6.png">

<img src="lesson_pages/7.png">

<img src="lesson_pages/7.png">

<img src="lesson_pages/8.png">

# EXAMPLE WITH IMPLICIT METHOD

In [8]:
# Create European Contract
# Create Market Model
# Create PDEParams
# Create GenericPDEPricer
# Calculate FV and Greeks based on Implicit method
# Visualize the Call and Put prices in 2D and 3D

<img src="lesson_pages/9.png">

<img src="lesson_pages/10.png">

<img src="lesson_pages/11.png">

# EXAMPLE WITH CRANK NICOLSON METHOD

In [7]:
# Create European Contract
# Create Market Model
# Create PDEParams
# Create GenericPDEPricer
# Calculate FV and Greeks based on Crank_Nicolson methods
# Visualize the Call and Put prices in 2D and 3D

# COMPARE PRICE AND GREEKS WITH EUROPEAN ANALYTICAL PRICER